version: '3.0'

services:
  grafana:
    container_name: 'grafana-dev-wildgraphql'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        # https://grafana.com/docs/grafana/latest/whatsnew/
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
        development: "true"
    cap_add:
      - SYS_PTRACE # To allow debugging with Delve
    security_opt:
      - seccomp:unconfined # To allow debugging with Delve
    ports:
      - "3000:3000/tcp"
      - "2345:2345/tcp"
    volumes:
      - ./dist:/var/lib/grafana/plugins/retrodaredevil-wildgraphql-datasource:ro
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./provisioned-dashboards:/provisioned-dashboards:ro
      - .:/root/retrodaredevil-wildgraphql-datasource:ro
  graphql-echo:
    container_name: 'grafana-dev-wildgraphql-graphql-echo'
    image: 'ghcr.io/retrodaredevil/graphql-echo:0.1'
